<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
       <groupId>org.springframework.boot</groupId>
       <artifactId>spring-boot-starter-parent</artifactId>
       <version>3.5.5</version>
       <relativePath/>
    </parent>

    <groupId>${groupId}</groupId>
    <artifactId>${artifactId}</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <modules>
        <module>api</module>
        <module>repository</module>
    </modules>

<properties>
    <java.version>17</java.version>
    <jwt.version>0.10.7</jwt.version>
    <mybatis-plus.version>3.5.14</mybatis-plus.version>
    <modelmapper.version>3.2.4</modelmapper.version>
    <hutool.version>5.8.41</hutool.version>
    <knife4j.version>4.5.0</knife4j.version>
    <redisson.version>3.51.0</redisson.version>
    <dynamic-datasource.version>4.3.1</dynamic-datasource.version>
    <sa-token.version>1.44.0</sa-token.version>
    <fastexcel.version>1.3.0</fastexcel.version>
    <spring-social.version>1.1.6.RELEASE</spring-social.version>
    <springdoc-maven-plugin.version>1.3</springdoc-maven-plugin.version>
    <p6spy.version>3.9.1</p6spy.version>
    <tianai-captcha.version>1.5.2</tianai-captcha.version>
    <justauth.version>1.16.7</justauth.version>
    <chatgpt.version>5.1.1</chatgpt.version>
    <ip2region.version>2.7.0</ip2region.version>
    <caffeine.version>3.2.3</caffeine.version>
    <jakarta.mail.version>2.1.5</jakarta.mail.version>
    <angus.mail.version>2.0.5</angus.mail.version>
    <tencentcloud.version>3.1.1366</tencentcloud.version>
    <annotations.version>26.0.2</annotations.version>
    <ve-tos.version>2.9.5</ve-tos.version>
    <jsonRepairjVersion>1.0.0</jsonRepairjVersion>
  </properties>

    <dependencyManagement>
     <dependencies>
      <!-- 项目内部模块依赖 -->
      <dependency>
          <groupId>com.example</groupId>
          <artifactId>api</artifactId>
          <version>${r'${project.version}'}</version>
      </dependency>
      <dependency>
          <groupId>com.example</groupId>
          <artifactId>repository</artifactId>
          <version>${r'${project.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-boot-starter</artifactId>
        <version>${r'${mybatis-plus.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-generator</artifactId>
        <version>${r'${mybatis-plus.version}'}</version>
      </dependency>
      <dependency>
        <groupId>org.modelmapper</groupId>
        <artifactId>modelmapper</artifactId>
        <version>${r'${modelmapper.version}'}</version>
      </dependency>
      <dependency>
        <groupId>cn.hutool</groupId>
        <artifactId>hutool-all</artifactId>
        <version>${r'${hutool.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.github.xiaoymin</groupId>
        <artifactId>knife4j-openapi3-jakarta-spring-boot-starter</artifactId>
        <version>${r'${knife4j.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>dynamic-datasource-spring-boot3-starter</artifactId>
        <version>${r'${dynamic-datasource.version}'}</version>
      </dependency>
      <dependency>
        <groupId>org.redisson</groupId>
        <artifactId>redisson-spring-boot-starter</artifactId>
        <version>${r'${redisson.version}'}</version>
      </dependency>
      <dependency>
        <groupId>me.zhyd.oauth</groupId>
        <artifactId>JustAuth</artifactId>
        <version>${r'${justauth.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.github.plexpt</groupId>
        <artifactId>chatgpt</artifactId>
        <version>${r'${chatgpt.version}'}</version>
      </dependency>
      <dependency>
        <groupId>cn.dev33</groupId>
        <artifactId>sa-token-spring-boot3-starter</artifactId>
        <version>${r'${sa-token.version}'}</version>
      </dependency>
      <dependency>
        <groupId>cn.dev33</groupId>
        <artifactId>sa-token-sign</artifactId>
        <version>${r'${sa-token.version}'}</version>
      </dependency>
      <dependency>
        <groupId>cn.dev33</groupId>
        <artifactId>sa-token-apikey</artifactId>
        <version>${r'${sa-token.version}'}</version>
      </dependency>
      <dependency>
        <groupId>cn.dev33</groupId>
        <artifactId>sa-token-jwt</artifactId>
        <version${r'>${sa-token.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.tencentcloudapi</groupId>
        <artifactId>tencentcloud-sdk-java-sms</artifactId>
        <version>3.1.1357</version>
      </dependency>
      <dependency>
        <groupId>com.tencentcloudapi</groupId>
        <artifactId>tencentcloud-sdk-java-common</artifactId>
        <version>${r'${tencentcloud.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.volcengine</groupId>
        <artifactId>ve-tos-java-sdk</artifactId>
        <version>2.9.5</version>
      </dependency>
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-jsqlparser</artifactId>
        <version>3.5.14</version>
      </dependency>
      <dependency>
        <groupId>p6spy</groupId>
        <artifactId>p6spy</artifactId>
        <version>${r'${p6spy.version}'}</version>
      </dependency>
      <dependency>
        <groupId>org.jetbrains</groupId>
        <artifactId>annotations</artifactId>
        <version>26.0.2-1</version>
      </dependency>
      <dependency>
        <groupId>org.lionsoul</groupId>
        <artifactId>ip2region</artifactId>
        <version>2.7.0</version>
      </dependency>
      <dependency>
        <groupId>cn.idev.excel</groupId>
        <artifactId>fastexcel</artifactId>
        <version>${r'${fastexcel.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.google.guava</groupId>
        <artifactId>guava</artifactId>
        <version>33.5.0-jre</version>
      </dependency>
      <dependency>
        <groupId>com.google.code.gson</groupId>
        <artifactId>gson</artifactId>
        <version>2.13.2</version>
      </dependency>
      <dependency>
        <groupId>org.mybatis</groupId>
        <artifactId>mybatis-spring</artifactId>
        <version>3.0.5</version>
      </dependency>
      <dependency>
        <groupId>com.baomidou</groupId>
        <artifactId>mybatis-plus-spring-boot3-starter</artifactId>
        <version>3.5.14</version>
      </dependency>
      <dependency>
        <groupId>org.springdoc</groupId>
        <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
        <version>2.7.0</version>
      </dependency>
      <dependency>
        <groupId>org.bouncycastle</groupId>
        <artifactId>bcprov-jdk15to18</artifactId>
        <version>1.83</version>
      </dependency>
      <dependency>
        <groupId>org.apache.tomcat</groupId>
        <artifactId>tomcat-coyote</artifactId>
        <version>11.0.14</version>
      </dependency>
      <dependency>
        <groupId>${groupId}</groupId>
        <artifactId>repository</artifactId>
        <version>${r'${project.version}'}</version>
      </dependency>
      <dependency>
        <groupId>${groupId}</groupId>
        <artifactId>web</artifactId>
        <version>${r'${project.version}'}</version>
      </dependency>
      <dependency>
        <groupId>${groupId}</groupId>
        <artifactId>common</artifactId>
        <version>${r'${project.version}'}</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jsr310</artifactId>
        <version>2.20.1</version>
      </dependency>
      <dependency>
        <groupId>com.fasterxml.jackson.datatype</groupId>
        <artifactId>jackson-datatype-jdk8</artifactId>
        <version>2.20.1</version>
      </dependency>
      <dependency>
        <groupId>org.freemarker</groupId>
        <artifactId>freemarker</artifactId>
        <version>2.3.34</version>
      </dependency>
      <dependency>
        <groupId>com.alibaba</groupId>
        <artifactId>transmittable-thread-local</artifactId>
        <version>2.14.5</version>
      </dependency>
      <dependency>
        <groupId>io.micrometer</groupId>
        <artifactId>micrometer-registry-prometheus</artifactId>
        <version>1.16.1</version>
      </dependency>
      </dependencies>
    </dependencyManagement>
</project>